config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "properties#index"
  resources :properties
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :user
    has_one_attached :image
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :properties       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/home_controller.rb
class  HomeController < ApplicationController
    
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    def index
        @properties = Property.all
    end

    def show
       @property = Property.find(params[:id])
    end

    def new
        @property = Property.new()
    end

    def create
        @property = current_user.properties.new(property_params)
        
        if @property.save
            redirect_to @property, notice: 'Property was successfully saved'
        else
            render :new
        end
    end

    def destroy
        @property = Property.find(params[:id])
        @property.destroy
        redirect_to properties_url, notice: 'Property was successfully destroyed'
    end

    def edit
        @property = Property.find(params[:id])
    end

    def update
        property = Property.find(params["id"])
        property.update(property_params)
        redirect_to property    
    end

    private
    def property_params
            params.require(:property).permit(:name, :bedrooms, :bathrooms, :parking_spaces, :information, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
pagina inicio
<div></div>
<%= link_to "New Property", new_property_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyCatalogue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-light" style="background-color: #eaec1f;">
  <a class="navbar-brand" href="/">Property Catalogue</a>
  <p class="navbar-text float-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">

    </ul>
    <span class="navbar-text">
      Navbar text with an inline element
    </span>
  </div>
  </nav>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

  
    <%= yield %>

  </body>
</html>

app/views/properties/edit.html.erb
<%= form_with model: @property do |form| %>
<h1> Edit Property </h1>

<% if current_user.id == @property.user_id %>
   

    <p>
    </p>

    <div class="field">
        <%= form.label :Name %>
        <%= form.text_field :name %>

    <div class="field">
        <%= form.label :Bedrooms %>
        <%= form.select :bedrooms,[1,2,3,4,5,6] %>
    </div>

    <div class="field">
        <%= form.label :Bathrooms %>
        <%= form.select :bathrooms, [1,2,3,4,5,6] %>
    </div>

    <div class="field">
        <%= form.label :Parking_Spaces %>
        <%= form.select :parking_spaces, [1,2,3,4,5,6] %>
    </div>

    <div class="field">
        <%= form.label :Information %>
        <%= form.text_area :information, size: "24x6" %>
    </div>

    <div class="field">
        <%= form.label :image %>
        <%= form.file_field :image %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
    <% end %>
<% end %>

app/views/properties/index.html.erb
<div class="container-fluid">

    <div class="jumbotron">
         <h1 class="display-3">Real estate properties...</h1>
        <p class="lead">More than just a place!</p>
        <hr class="my-3">
        <p>Create a new property:</p>
        <p class="lead">
        <%= link_to "New Property", new_property_path, class: "btn btn-primary" %>
        </p>
    </div>

  
    <div class="row">
        <% @properties.each do |property| %>
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <%= link_to(image_tag(property.image, class: "card-img-top"), property) %>
                    <div class="card-body">
                        <h1 class="card-title"><%= property.name %></h1>
                        <p class="card-text"><%= property.user_id %></p>
                        <p class="card-text"><%= property.information %></p>
                        <% if user_signed_in? && current_user.id == property.user_id%>
                            <%= button_to "Edit", "/properties/#{property.id}/edit", method: :get, class: "btn btn-info" %>

                            <%= button_to "Delete", property, method: :delete, class: "btn btn-danger"%>

                        <% end %>
                    </div>
                </div>

            </div>
        
    
        <% end %>
    </div>

</div>

app/views/properties/new.html.erb
<%= form_with model: @property do |form| %>
<h1> New Property </h1>

<p>
</p>

<div class="field">
    <%= form.label :Name %>
    <%= form.text_field :name %>

<div class="field">
    <%= form.label :Bedrooms %>
    <%= form.select :bedrooms,[1,2,3,4,5,6] %>
</div>

<div class="field">
    <%= form.label :Bathrooms %>
    <%= form.select :bathrooms, [1,2,3,4,5,6] %>
</div>

<div class="field">
    <%= form.label :Parking_Spaces %>
    <%= form.select :parking_spaces, [1,2,3,4,5,6] %>
</div>

<div class="field">
    <%= form.label :Information %>
    <%= form.text_area :information, size: "24x6" %>
</div>

<div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/properties/show.html.erb
<div class="field">
    
    
<label>Property Name:</label>
<div></div>
<h1><%= @property.name %></h1>
<div></div>
<label>User:</label>
<div></div>
<h1><%= @property.user_id %></h1>
<div></div>
<label>Bedrooms:</label>
<div></div>
<h1><%= @property.bedrooms %></h1>
<div></div>
<label>Bathrooms:</label>
<div></div>
<h1><%= @property.bathrooms %></h1>
<div></div>
<label>Parking Spaces:</label>
<div></div>
<h1><%= @property.parking_spaces %></h1>
<div></div>
<label>Property Information:</label>
<div></div>
<h1><%= @property.information %></h1>

<% if current_user.id == @property.user_id%>
    <%= button_to "Edit", "/properties/#{@property.id}/edit", method: :get %>

    <%= button_to "Delete", @property, method: :delete%>

    <% end %>

<%= image_tag(@property.image, style: "width: 90vw") if @property.image.attached? %>